#' Calculate chromatographic peak properties
#'
#' Calculate the ppm error, retention time deviation, FWHM, number of scans, tailing factor and asymmetry factor for each measured feature.
#'
#' @param rawSpec an \code{\link[MSnbase]{OnDiskMSnExp-class}}
#' @param targetFeatTable a \code{\link{data.frame}} of compounds to target as rows. Columns: \code{cpdID} (str), \code{cpdName} (str), \code{rtMin} (float in seconds), \code{rt} (float in seconds, or \emph{NA}), \code{rtMax} (float in seconds), \code{mzMin} (float), \code{mz} (float or \emph{NA}), \code{mzMax} (float).
#' @param foundPeakTable a \code{data.frame} as generated by \code{\link{findTargetFeatures}}, with features as rows and peak properties as columns. The following columns are mandatory: \code{mz}, \code{rt}, \code{scmin}, \code{scpos}, \code{scmax}, \code{sigma}.
#' @param usePreviousEICs (list of S4 \code{\link[MSnbase]{Chromatogram-class}} or NULL) If not NULL, use the inputed list of EICs (corresponding to each ROI) for statistics. If NULL, the EICs will be extracted from \code{rawSpec} during the function. Only use this option to reduce the number of file reads (EICs are obtained using \code{EICs <- xcms::chromatogram(rawSpec, rt = data.frame(rt_lower=targetFeatTable$rtMin, rt_upper=targetFeatTable$rtMax), mz = data.frame(mz_lower=targetFeatTable$mzMin, mz_upper=targetFeatTable$mzMax))}). If the EICs provided do not match the spectra, the statistics will be erronous.
#' @param verbose (bool) if TRUE message when NA scans are removed
#'
#' @return A \code{data.frame} with measured compounds as rows and measurements and properties as columns (see Details).
#'
#' \subsection{Details:}{
#'   The returned \code{data.frame} is structured as follow:
#'   \tabular{ll}{
#'     cpdID \tab database compound ID (if in input)\cr
#'     cpdName \tab compound name (if in input)\cr
#'     found \tab (bool) TRUE if compound was found in the raw data\cr
#'     mz \tab weighted (by intensity) mean of peak m/z across scans\cr
#'     mzmin \tab m/z peak minimum\cr
#'     mzmax \tab m/z peak maximum\cr
#'     rt \tab retention time of peak midpoint\cr
#'     rtmin \tab leading edge of peak retention time\cr
#'     rtmax \tab trailing edge of peak retention time\cr
#'     into \tab integrated peak intensity\cr
#'     intb \tab baseline corrected integrated peak intensity\cr
#'     maxo \tab maximum peak intensity\cr
#'     sn \tab Signal/Noise ratio, defined as \code{(maxo - baseline)/sd}, where \code{maxo} is the maximum peak intensity, \code{baseline} the estimated baseline value and \code{sd} the standard deviation of local chromatographic noise.\cr
#'     egauss \tab RMSE of Gaussian fit\cr
#'     mu \tab Gaussian parameter mu\cr
#'     sigma \tab Gaussian parameter sigma\cr
#'     h \tab Gaussian parameter h\cr
#'     f \tab Region number of m/z ROI where the peak was localised\cr
#'     dppm \tab m/z deviation of mass trace across scans in ppm\cr
#'     scale \tab Scale on which the peak was localised\cr
#'     scpos \tab Peak position found by wavelet analysis (scan number)\cr
#'     scmin \tab Left peak limit found by wavelet analysis (scan number)\cr
#'     scmax \tab Right peak limit found by wavelet analysis (scan number)\cr
#'     ppm_error \tab difference in ppm between the expected and measured m/z\cr
#'     rt_dev_sec \tab difference in seconds between the expected and measured rt\cr
#'     FWHM \tab full width at half maximum (in seconds), not available if \code{fitGauss=FALSE}\cr
#'     FWHM_ndatapoints \tab number of scans on the peak\cr
#'     tailingFactor \tab the tailing factor is a measure of peak tailing.It is defined as the distance from the front slope of the peak to the back slope divided by twice the distance from the center line of the peak to the front slope, with all measurements made at 5\% of the maximum peak height. The tailing factor of a peak will typically be similar to the asymmetry factor for the same peak, but the two values cannot be directly converted\cr
#'     asymmetryFactor \tab the asymmetry factor is a measure of peak tailing. It is defined as the distance from the center line of the peak to the back slope divided by the distance from the center line of the peak to the front slope, with all measurements made at 10\% of the maximum peak height. The asymmetry factor of a peak will typically be similar to the tailing factor for the same peak, but the two values cannot be directly converted\cr
#'   }
#' }
#'
#' @references Adapted for XCMS3 from Jan Stanstrup https://cdn.rawgit.com/stanstrup/QC4Metabolomics/master/MetabolomiQCsR/inst/doc/standard_stats.html#calculating-statistics
#'
#' @examples
#' \dontrun{
#' ## Load data
#' library(faahKO)
#' library(MSnbase)
#' netcdfFilePath <- system.file('cdf/KO/ko15.CDF', package = "faahKO")
#' raw_data       <- MSnbase::readMSData(netcdfFilePath, centroided=TRUE, mode='onDisk')
#'
#' ## targetFeatTable
#' targetFeatTable     <- data.frame(matrix(vector(), 2, 8, dimnames=list(c(), c("cpdID",
#'                          "cpdName", "rtMin", "rt", "rtMax", "mzMin", "mz", "mzMax"))),
#'                          stringsAsFactors=F)
#' targetFeatTable[1,] <- c("ID-1", "Cpd 1", 3310., 3344.888, 3390., 522.194778, 522.2, 522.205222)
#' targetFeatTable[2,] <- c("ID-2", "Cpd 2", 3280., 3385.577, 3440., 496.195038, 496.2, 496.204962)
#' targetFeatTable[,c(1,3:8)] <- sapply(targetFeatTable[,c(1,3:8)], as.numeric)
#'
#' ROIList        <- makeROIList(raw_data, targetFeatTable)
#'
#' foundPeakTable <- findTargetFeatures(raw_data, ROIList)
#'
#' peakStatistics <- getTargetFeatureStatistic(raw_data, targetFeatTable, foundPeakTable)
#' peakStatistics
#' #    found    mz mzmin mzmax       rt    rtmin    rtmax     into     intb   maxo    sn egauss mu
#' # 1   TRUE 522.2 522.2 522.2 3344.888 3322.979 3379.317 25792525 25768308 889280  1840     NA NA
#' # 2   TRUE 496.2 496.2 496.2 3382.447 3362.102 3409.051 32873727 32818664 1128960 1471     NA NA
#' #    sigma h  f dppm scale scpos scmin scmax lmin lmax sample is_filled   ppm_error rt_dev_sec
#' # 1     NA NA 1    0     5   540   535   545   24   60      1         0  0.02336270       0.00
#' # 2     NA NA 2    0     5   564   559   569   68   98      1         0  0.02458686       3.13
#' #    FWHM FWHM_ndatapoints tailingFactor asymmetryFactor
#' # 1    NA               11            NA        1.484000
#' # 2    NA               11            NA        2.708291
#' }
getTargetFeatureStatistic <- function(rawSpec, targetFeatTable, foundPeakTable, usePreviousEICs=NULL, verbose=FALSE) {

  ## Define the peak_shape_stat() -----------------------
  #
  # Calculate tailing factor and asymmetry factor
  #
  # Tailing Factor and Asymmetry Factor following the equations from http://www.chromforum.org/viewtopic.php?t=20079
  #
  # @param featEIC A single EIC as generated by \code{\link[xcms]{chromatogram}}
  # @param apexRT (float) retention time in seconds of the measured peak apex
  # @param statistic (str) either \code{tailingFactor} or \code{asymmetryFactor}
  # @param verbose (bool) if TRUE message when NA scans are removed
  #
  # @return Tailing factor or Asymmetry factor value
  #
  # @references Adapted for XCMS3 from QC4Metabolomics by Jan Stanstrup https://github.com/stanstrup/QC4Metabolomics/blob/master/MetabolomiQCsR/R/standard_stats.R
  # @references Equations from http://www.chromforum.org/viewtopic.php?t=20079
  #
  peak_shape_stat <- function(featEIC, apexRT, statistic="tailingFactor", verbose=FALSE){

    # A B and C are retention time in seconds. C is RT of the apex, A is left side as x%, B is right side at x%. x% (cutoff) depends of the statistic employed.

    #check inputs
    if(is.na(apexRT)) return(NA)

    # Remove scans with intensity NA from the feature
    if (sum(is.na(xcms::intensity(featEIC))) != 0) {
      if(verbose){
        message(sum(is.na(xcms::intensity(featEIC))), '/', length(xcms::intensity(featEIC)), ' scans removed due to NA')
      }
      filterNA    <- !is.na(xcms::intensity(featEIC))
      featEIC_RT  <- xcms::rtime(featEIC)[filterNA]
      featEIC_Int <- xcms::intensity(featEIC)[filterNA]
    } else {
      featEIC_RT  <- xcms::rtime(featEIC)
      featEIC_Int <- xcms::intensity(featEIC)
    }

    # get the scan number of the RT apex
    apexRT_scan_number <- which.min(abs(featEIC_RT - apexRT))
    # the RT matching this apex (also known as C)
    C   <- featEIC_RT[apexRT_scan_number]

    # ensure we don't overshoot the index
    # -2 / +2
    if( (apexRT_scan_number-2)>=1 ){ startRange2pt <- apexRT_scan_number-2 }
    else { startRange2pt <- 1}
    if( (apexRT_scan_number+2)<=length(featEIC_RT) ){ endRange2pt <- apexRT_scan_number+2 }
    else { endRange2pt <- length(featEIC_RT) }
    # -1 / +1
    if( (apexRT_scan_number-1)>=1 ){ startRange1pt <- apexRT_scan_number-1 }
    else { startRange1pt <- 1}
    if( (apexRT_scan_number+1)<=length(featEIC_RT) ){ endRange1pt <- apexRT_scan_number+1 }
    else { endRange1pt <- length(featEIC_RT) }

    # maximum intensity across the 5 central scans to avoid problems if the center is not the highest
    max_int <- max(featEIC_Int[startRange2pt:endRange2pt], na.rm = TRUE)

    # check values are non-0 for 3 central scans, otherwise exit
    if( all( featEIC_Int[(startRange1pt):(endRange1pt)] == 0) ) return(NA)


    # Median smoothing. Avoids single zero values breaking things. Already smooth peaks are unaffected.
    if(  !all( c(featEIC_Int[startRange1pt], featEIC_Int[endRange1pt]) == 0 )  ){ # If the values on each side of the mid of the peak are both 0 don't do smoothing (a 1 scan spike would cause this).
      featEIC_Int  <- stats::smooth(featEIC_Int, kind="3")
    }


    # If middle scan is zero after smoothing, exit
    if( featEIC_Int[apexRT_scan_number] == 0 ) return(NA)


    # Left side of the peak
    # Get each scan RT, reverse order, normalise by max_intensity (so just need to look for x% (cutoff) no need to divide later)
    A_side_rt       <- rev(featEIC_RT[1:apexRT_scan_number]) # can use featEIC as RT didn't change
    # Get scan, reverse order, normalise by max_intensity (so just need to look for x% (cutoff) no need to divide later)
    A_side_normInt  <- rev(featEIC_Int[1:apexRT_scan_number])/max_int

    # Right side of the peak
    # Get each scan RT
    B_side_rt       <- featEIC_RT[apexRT_scan_number:length(MSnbase::rtime(featEIC))] # can use featEIC as RT didn't change
    # Get scan, normalise by max_intensity
    B_side_normInt  <- featEIC_Int[apexRT_scan_number:length(featEIC_Int)]/max_int


    # Change the cut-off depending on the statistic
    cutoff <- switch(statistic, tailingFactor=0.05, asymmetryFactor=0.1)

    ## Get A (left side)
    # Keep points all points > cutoff and 1 point < cutoff, then interpolate cutoff retention time
    A_cutoff_pt     <- match(-1,sign(A_side_normInt - cutoff)) # positions of scans up to when it's too far (if negative, we are past the cutoff)
    if (!is.na(A_cutoff_pt)) {
      A_scans_toKeep  <- seq(1, A_cutoff_pt)
      A_side_rt       <- A_side_rt[A_scans_toKeep]
      A_side_normInt  <- A_side_normInt[A_scans_toKeep]
      # Check there was a point over cutoff (only 1 point, can't work)
      if( length(A_scans_toKeep)==1 ) return(NA)
    } else {
      return(NA)
    }

    # Approximate the RT at the cutoff intensity
    A <- stats::approx(x=A_side_normInt, y=A_side_rt, xout=cutoff)$y


    # Get B (right side)
    # Keep points all points > cutoff and 1 point < cutoff, then interpolate cutoff retention time
    B_cutoff_pt     <- match(-1,sign(B_side_normInt - cutoff)) # positions of scans up to when it's too far (if negative, we are past the cutoff)
    if (!is.na(B_cutoff_pt)) {
      B_scans_toKeep  <- seq(1, B_cutoff_pt)
      B_side_rt       <- B_side_rt[B_scans_toKeep]
      B_side_normInt  <- B_side_normInt[B_scans_toKeep]
      # Check there was a point over cutoff (only 1 point, can't work)
      if( length(B_scans_toKeep)==1 ) return(NA)
    } else {
      return(NA)
    }

    # Approximate the RT at the cutoff intensity
    B <- stats::approx(x=B_side_normInt, y=B_side_rt, xout=cutoff)$y

    # remove the name from the named float
    if(statistic=="tailingFactor") {
      result <- (B-A)/(2*(C-A))
      return( result[[1]] )
    }
    if(statistic=="asymmetryFactor") {
      result <- (B-C)/(C-A)
      return( result[[1]] )
    }
  }
  ## ----------------------------------------------------

	stime <- Sys.time()

  if (dim(targetFeatTable)[1] != dim(foundPeakTable)[1]) {
    stop("Number of features in targetFeatTable (", dim(targetFeatTable)[1],") and foundPeakTable (", dim(foundPeakTable)[1], ") do not match!")
  }

	if (all(!is.null(usePreviousEICs))) {
		if (!is.list(usePreviousEICs)) {
			stop("usePreviousEICs is not a list of xcms::Chromatogram")
		}
		if (length(usePreviousEICs) != dim(targetFeatTable)[1]) {
			stop("Number of chromatograms in usePreviousEICs (", length(usePreviousEICs),") and features in targetFeatTable (", dim(targetFeatTable)[1], ") do not match!")
		}
		if (!methods::is(usePreviousEICs[[1]], 'Chromatogram')) {
			stop("usePreviousEICs is not a list of xcms::Chromatogram")
		}
	}

	## Extract all EICs from raw data (found features) if none passed as input
	if (all(!is.null(usePreviousEICs))) {
		if (verbose) { message("Previously loaded EICs used for peak statistics") }
		EICs 	<- usePreviousEICs
	} else {
		EICs	<- xcms::chromatogram(rawSpec, rt = data.frame(rt_lower=targetFeatTable$rtMin, rt_upper=targetFeatTable$rtMax), mz = data.frame(mz_lower=targetFeatTable$mzMin, mz_upper=targetFeatTable$mzMax))
	}

  ## Calculate the statistics
  peakStat	<- data.frame(matrix(vector(), dim(targetFeatTable)[1], 6, dimnames=list(c(), c("ppm_error", "rt_dev_sec", "FWHM", "FWHM_ndatapoints", "tailingFactor", "asymmetryFactor"))), stringsAsFactors=F)

  for (i in 1:dim(targetFeatTable)[1]) {
    # If the feature wasn't found we cannot work with it
    if (foundPeakTable$found[i]) {
      # ppm_error
      if (!is.na(targetFeatTable$mz[i])) {
        peakStat$ppm_error[i] <- (abs(foundPeakTable$mz[i] - targetFeatTable$mz[i])/targetFeatTable$mz[i])*1E6
      }
      # rt_dev_sec
      if (!is.na(targetFeatTable$rt[i])) {
        peakStat$rt_dev_sec[i] <- abs(foundPeakTable$rt[i] - targetFeatTable$rt[i])
      }

      # FWHM
      # need a function to approximate retention time between the existing scans
      if ((foundPeakTable$scpos[i]!=-1) & (foundPeakTable$scmin[i]!=-1) & (foundPeakTable$scmax[i]!=-1)) {
        approx_rt_from_scan <- stats::approxfun( seq_along( xcms::rtime(rawSpec)), xcms::rtime(rawSpec) ) # approximation of RT at any scan (even not integer)
        FWHM_scan           <- 2*sqrt(2*log(2))*foundPeakTable$sigma[i]
        FWHM_start          <- approx_rt_from_scan(foundPeakTable$scpos[i] - FWHM_scan/2) # min rt at half height (calculate the min scan at half height, convert to a RT with approx function)
        FWHM_end            <- approx_rt_from_scan(foundPeakTable$scpos[i] + FWHM_scan/2)
        peakStat$FWHM[i]             <- FWHM_end - FWHM_start
        peakStat$FWHM_ndatapoints[i] <- (foundPeakTable$scmax[i] - foundPeakTable$scmin[i]) + 1 # number of datapoints for peak measurement
      }
      # Tailing Factor
      peakStat$tailingFactor[i]      <- peak_shape_stat(EICs[[i]], foundPeakTable$rt[i], statistic = "tailingFactor")
      # Asymmetry Factor
      peakStat$asymmetryFactor[i]   <- peak_shape_stat(EICs[[i]], foundPeakTable$rt[i], statistic = "asymmetryFactor")
    }
  }

  ## group the results and return
  finalTable  <- cbind.data.frame(foundPeakTable, peakStat)

	etime <- Sys.time()
	if (verbose) {
    message('Peak statistics done in: ', round(as.double(difftime(etime,stime)),2),' ',units( difftime(etime,stime)))
  }

  return( finalTable )
}
