#' Save to disk a plot of all ROI EIC and detected feature range
#'
#' Plot and save a \code{.png} of all ROI (x is RT, y is intensity), with the matching detected peak rt and peakwidth under it.
#'
#' @param EICs (list) list of xcms::chromatograms (one per ROI, same order as rows in foundPeakTable)
#' @param foundPeakTable (data.frame) \code{data.frame} as generated by \code{\link{findTargetFeatures}}, with features as rows and peak properties as columns. The following columns are mandatory: \code{cpdID}, \code{cpdName}, \code{rt}, \code{rtmin}, \code{rtmax}, \code{mzmin}, \code{mzmax}.
#' @param savePath (str) Full path to save a \emph{.png} of all ROI EICs , expect \code{'filepath/filename.png'}.
#' @param width (float) Width in cm for a single ROI plot (if more than one plot in total, 2 columns will be used). dpi set to a 100.
#' @param height (float) height in a cm for a single ROI plot. dpi set to 100
#' @param verbose (bool) if TRUE message progress
#'
#' @return None
saveMultiEIC   <- function(EICs, foundPeakTable, savePath, width=15, height=15, verbose=TRUE) {

  ## check input
  if (length(EICs) != dim(foundPeakTable)[1]) {
    stop("Number of chromatograms in EICs (", length(EICs),") and features in foundPeakTable (", dim(foundPeakTable)[1], ") do not match!")
  }

  ## Generate each ROI plot
  p_all         <- vector("list", length(EICs))
  for (i in 1:length(EICs)) {
    p_all[[i]]  <- plotEICDetectedPeakwidth(EICs[[i]], foundPeakTable$cpdID[i], foundPeakTable$cpdName[i], foundPeakTable$rt[i], foundPeakTable$rtmin[i], foundPeakTable$rtmax[i], foundPeakTable$mzmin[i], foundPeakTable$mzmax[i])
  }

  ## Set save parameters
  targetFolder  <- dirname(savePath)
  targetFile    <- basename(savePath)
  nSubplot      <- length(p_all)

  if (nSubplot==1) {
    ncol    <- 1
  } else {
    ncol    <- 2
    nrow    <- ceiling(nSubplot/2)
    width   <- width * ncol
    height  <- height * nrow
  }

  ## Save
  ggplot2::ggsave(file=targetFile, plot=gridExtra::arrangeGrob(grobs=p_all, ncol=ncol), device='png', path=targetFolder, dpi=100, width=width, height=height, units='cm', limitsize=FALSE)

  if (verbose) { message('Summary EIC plot saved at: ', savePath)}
}
